services:
 web:
    container_name: web
    build: .
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: bewise_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: bewise
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"
